// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet_DotNet.Data;

#nullable disable

namespace Projet_DotNet.Migrations
{
    [DbContext(typeof(GestionDbContext))]
    [Migration("20241214112930_App")]
    partial class App
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Projet_DotNet.Models.Departement", b =>
                {
                    b.Property<int>("DepartementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartementId"));

                    b.Property<string>("NomDepartement")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("DepartementId");

                    b.ToTable("Departements", "HR");
                });

            modelBuilder.Entity("Projet_DotNet.Models.Employe", b =>
                {
                    b.Property<int>("EmployeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeId"));

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartementId")
                        .HasColumnType("int");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("varchar(5)");

                    b.Property<string>("NomEmploye")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PrenomEmploye")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("Salaire")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("UserImage")
                        .HasColumnType("varchar(206)");

                    b.HasKey("EmployeId");

                    b.HasIndex("DepartementId");

                    b.ToTable("Employes", "HR");
                });

            modelBuilder.Entity("Projet_DotNet.Models.Employe", b =>
                {
                    b.HasOne("Projet_DotNet.Models.Departement", "Departement")
                        .WithMany()
                        .HasForeignKey("DepartementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departement");
                });
#pragma warning restore 612, 618
        }
    }
}
